# Generated by Django 4.0.3 on 2025-09-22 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_ru', models.PositiveSmallIntegerField(default=42)),
                ('largest_free', models.PositiveSmallIntegerField(default=0)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='racks.datacenter')),
            ],
        ),
        migrations.CreateModel(
            name='FreeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ru', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_blocks', to='racks.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ru', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='racks.rack')),
            ],
        ),
    ]
