# Generated by Django 4.0.3 on 2025-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='original_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
